// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqlGzkzVXSyNLVIiON4v_jalA-I44VL5A',
    appId: '1:571300791191:web:a87a70584ae208bddffad2',
    messagingSenderId: '571300791191',
    projectId: 'urbangreen-3f832',
    authDomain: 'urbangreen-3f832.firebaseapp.com',
    storageBucket: 'urbangreen-3f832.appspot.com',
    measurementId: 'G-BQ9FDSL2NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvvkRE4GDoicFQD-wOB6EyJvY1jZXVzw',
    appId: '1:571300791191:android:1176c6733d3498d8dffad2',
    messagingSenderId: '571300791191',
    projectId: 'urbangreen-3f832',
    storageBucket: 'urbangreen-3f832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGdWSpim2CPGJ4aB21YTtD62vMi4U2Og',
    appId: '1:571300791191:ios:1eec5b86280ac4b3dffad2',
    messagingSenderId: '571300791191',
    projectId: 'urbangreen-3f832',
    storageBucket: 'urbangreen-3f832.appspot.com',
    iosClientId: '571300791191-fta83ldau2q5eg7git20ti0pgjafljsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbangreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhGdWSpim2CPGJ4aB21YTtD62vMi4U2Og',
    appId: '1:571300791191:ios:1eec5b86280ac4b3dffad2',
    messagingSenderId: '571300791191',
    projectId: 'urbangreen-3f832',
    storageBucket: 'urbangreen-3f832.appspot.com',
    iosClientId: '571300791191-fta83ldau2q5eg7git20ti0pgjafljsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbangreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqlGzkzVXSyNLVIiON4v_jalA-I44VL5A',
    appId: '1:571300791191:web:5911f07f4e69cd4edffad2',
    messagingSenderId: '571300791191',
    projectId: 'urbangreen-3f832',
    authDomain: 'urbangreen-3f832.firebaseapp.com',
    storageBucket: 'urbangreen-3f832.appspot.com',
    measurementId: 'G-LWN0CC1WCD',
  );
}
